Repository SpiNNakerManchester/spinnaker_tools, pull requests merged in 2020-11, with the labels that each got.

#145 Move to GitHub Actions
  .github/workflows/c_actions.yml
  .gitignore
Labels: enhancement

#146 Publish action
  .github/workflows/publish.yml
  .travis.yml
Labels: enhancement

#147 Add a badge to track the build status, in common with other repos
  README.md
Labels: cosmetic, enhancement

#148 Get arm-none-eabi-gcc via apt-get rather than using specific action
  .github/workflows/c_actions.yml
Labels: bug
