Repository SpiNNakerManchester/spinnaker_tools, pull requests merged in 2020-09, with the labels that each got.

#128 Convert some_fun() to some_fun(void)
  apps/pt_demo/tracer.c
  apps/sdping/sdping.c
  apps/simple/simple.c
  bmp/bmp_crc.c
  sark/sark_base.c
  sark/sark_hw.c
  spin1_api/spin1_api.c
  spin1_api/spin1_isr.c
Labels: enhancement

#133 Fix for armcc
  Jenkinsfile
  include/.gitignore
  include/sark.h
  include/scamp_spin1_sync.h
  include/spinnaker.h
  include/version.h
  release.txt
  sark/sark_alloc.c
  scamp/scamp-3.c
  scamp/scamp-app.c
  scamp/scamp-boot.c
  scamp/scamp-del.c
  scamp/scamp-isr.c
  scamp/scamp-nn.c
  scamp/scamp.h
  spin1_api/spin1_api.c
  spin1_api/spin1_isr.c
Labels: bug

#135 Add link to info
  scamp/scamp-cmd.c
Labels: enhancement

#107 Sort out memory barriers for spin1api
  include/spin1_api.h
  spin1_api/spin1_api.c
Labels: review required
